version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn fragrance.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/backend/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volume:
      - static_volume:/home/app/backend/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: